lib/sample_app_web/router.ex
defmodule SampleAppWeb.Router do
  use SampleAppWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
#    plug :put_root_layout, {SampleAppWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", SampleAppWeb do
    pipe_through :browser

    get "/", StaticPageController, :home, as: :root
    get "/help", StaticPageController, :help, as: :help
    get "/about", StaticPageController, :about, as: :about
    get "/contact", StaticPageController, :contact, as: :contact
    get "/signup", UserController, :new, as: :signup
  end

  # Other scopes may use custom stacks.
  # scope "/api", SampleAppWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: SampleAppWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/sample_app/accounts.ex
defmodule SampleApp.Accounts do
  alias SampleApp.Repo
  alias SampleApp.Accounts.User

  def authenticate_by_email_and_pass(email, given_pass) do
    user = Repo.get_by(User, email: email)

    cond do
      user && Argon2.verify_pass(given_pass, user.password_hash) ->
        {:ok, user}

      user ->
        {:error, :unauthorized}

      true ->
        Argon2.no_user_verify()
        {:error, :not_found}
    end
  end
  @moduledoc """
  The Accounts context.
  """

  import Ecto.Query, warn: false
  alias SampleApp.Repo

  alias SampleApp.Accounts.User

  @doc """
  Returns the list of users.

  ## Examples

      iex> list_users()
      [%User{}, ...]

  """
  def list_users do
    Repo.all(User)
  end

  @doc """
  Gets a single user.

  Raises `Ecto.NoResultsError` if the User does not exist.

  ## Examples

      iex> get_user!(123)
      %User{}

      iex> get_user!(456)
      ** (Ecto.NoResultsError)

  """
  def get_user!(id), do: Repo.get!(User, id)

  @doc """
  Creates a user.

  ## Examples

      iex> create_user(%{field: value})
      {:ok, %User{}}

      iex> create_user(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_user(attrs \\ %{}) do
    %User{}
    |> User.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a user.

  ## Examples

      iex> update_user(user, %{field: new_value})
      {:ok, %User{}}

      iex> update_user(user, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_user(%User{} = user, attrs) do
    user
    |> User.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a user.

  ## Examples

      iex> delete_user(user)
      {:ok, %User{}}

      iex> delete_user(user)
      {:error, %Ecto.Changeset{}}

  """
  def delete_user(%User{} = user) do
    Repo.delete(user)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking user changes.

  ## Examples

      iex> change_user(user)
      %Ecto.Changeset{data: %User{}}

  """
  def change_user(%User{} = user) do
    User.changeset(user, %{})
  end

  def get_user(id) do
    Repo.get(User, id)
  end

  def get_user_by(params) do
    Repo.get_by(User, params)
  end

  def get_user_by!(params) do
    Repo.get_by!(User, params)
  end
end

lib/sample_app/accounts/user.ex
defmodule SampleApp.Accounts.User do
  use Ecto.Schema
  import Ecto.Changeset

  @valid_email_regex ~r/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  @required_fields [:name, :email, :password, :password_confirmation]

  schema "users" do
    field :email, :string
    field :name, :string
    field :password_hash, :string
    field :password, :string, virtual: true
    field :password_confirmation, :string, virtual: true
    timestamps()
  end

  @doc false
  def changeset(user, attrs) do
    user
    |> cast(attrs, @required_fields)
    |> validate_required(@required_fields)
    |> cast(attrs, [:name, :email])
    |> validate_required([:name, :email])
    |> validate_length(:name, max: 50)
    |> validate_length(:email, max: 255)
    |> validate_confirmation(:password, message: "does not match password")
    |> validate_length(:password, min: 6)
    |> validate_format(:email, @valid_email_regex)
    |> update_change(:email, &String.downcase/1)
    |> unique_constraint(:email)
    |> put_password_hash()
  end

  defp put_password_hash(changeset) do
    case changeset do
      %Ecto.Changeset{valid?: true, changes: %{password: password}} ->
        if password do
          put_change(changeset, :password_hash, Argon2.hash_pwd_salt(password))
        else
          changeset
        end
      _ ->
        changeset
    end
  end
end

lib/sample_app/application.ex
defmodule SampleApp.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  @impl true
  def start(_type, _args) do
    children = [
      # Start the Ecto repository
      SampleApp.Repo,
      # Start the Telemetry supervisor
      SampleAppWeb.Telemetry,
      # Start the PubSub system
      {Phoenix.PubSub, name: SampleApp.PubSub},
      # Start the Endpoint (http/https)
      SampleAppWeb.Endpoint
      # Start a worker by calling: SampleApp.Worker.start_link(arg)
      # {SampleApp.Worker, arg}
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: SampleApp.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  @impl true
  def config_change(changed, _new, removed) do
    SampleAppWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/sample_app/mailer.ex
defmodule SampleApp.Mailer do
  use Swoosh.Mailer, otp_app: :sample_app
end

lib/sample_app/repo.ex
defmodule SampleApp.Repo do
  use Ecto.Repo,
    otp_app: :sample_app,
    adapter: Ecto.Adapters.Postgres
end

lib/sample_app_web/controllers/page_controller.ex
defmodule SampleAppWeb.PageController do
  use SampleAppWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end

  def hello(conn, _params) do
    html(conn, "hello, world!")
  end
end

lib/sample_app_web/controllers/user_controller.ex
defmodule SampleAppWeb.UserController do
  use SampleAppWeb, :controller

  def new(conn, _params) do
    render(conn, "new.html")
  end
end

lib/sample_app_web/static_page_controller.ex
defmodule SampleAppWeb.StaticPageController do
  use SampleAppWeb, :controller

  def home(conn, _params) do
    render(conn, "home.html")
  end

  def help(conn, _params) do
    render(conn, "help.html")
  end

  def about(conn, _params) do
    render(conn, "about.html")
  end

  def contact(conn, _params) do
    render(conn, "contact.html", %{action: :contact})
  end
end

lib/sample_app_web/views/error_view.ex
defmodule SampleAppWeb.ErrorView do
  use SampleAppWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/sample_app_web/views/layout_view.ex
defmodule SampleAppWeb.LayoutView do
  use SampleAppWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

lib/sample_app_web/views/page_view.ex
defmodule SampleAppWeb.PageView do
  use SampleAppWeb, :view
end

lib/sample_app_web/views/static_page_view.ex
defmodule SampleAppWeb.StaticPageView do
  use SampleAppWeb, :view
end

lib/sample_app_web/views/user_view.ex
defmodule SampleAppWeb.UserView do
  use SampleAppWeb, :view
end

lib/sample_app_web/templates/layout/_footer.html.heex
<footer class="footer">
  <div class="container">
    <small>
      The <a href="#">Phoenix Tutorial</a>
      by <a href="#">Binh Tran</a>
    </small>
    <nav>
      <ul>
        <li><%= link "About", to: Routes.about_path(@conn, :about) %></li>
        <li><%= link "Contact", to: Routes.contact_path(@conn, :contact) %></li>
      </ul>
    </nav>
  </div>
</footer>

lib/sample_app_web/templates/layout/_header.html.heex
<header>
  <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <%= link "sample app", to: Routes.root_path(@conn, :home),
      id: "logo", class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
      data-bs-target="#navbarNav" aria-controls="navbarNav"
      aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse ms-auto" id="navbarNav">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <%= link "Home", to: Routes.root_path(@conn, :home),
            class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link "Help", to: Routes.help_path(@conn, :help),
            class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link "Log in", to: "#" , class: "nav-link" %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

lib/sample_app_web/templates/layout/_styles.html.heex
<link rel="stylesheet"
href={Routes.static_path(@conn, "/assets/app.css")} />

lib/sample_app_web/templates/layout/app.html.heex
<!DOCTYPE html>
<html>
  <head>
    <title>
    <%= SampleAppWeb.DynamicTextHelpers.page_title(Enum.into(assigns,
    %{view_module: @conn.private.phoenix_view, action: @conn.private.
    phoenix_action})) %>
    </title>
    <%= render "_styles.html", assigns %>
  </head>
  <body>
    <%= render "_header.html", assigns %>
    <div class="container mt-4">
      <%= @inner_content %>
      <%= render "_footer.html", assigns %>
    </div>
  <script type="text/javascript"
  src={ Routes.static_path(@conn, "/assets/app.js")}></script>
  </body>
</html>

lib/sample_app_web/templates/layout/live.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

lib/sample_app_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "SampleApp", suffix: " · Phoenix Framework" %>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")}/>
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
  </head>
  <body>
    <header>
      <section class="container">
        <nav>
          <ul>
            <li><a href="https://hexdocs.pm/phoenix/overview.html">Get Started</a></li>
            <%= if function_exported?(Routes, :live_dashboard_path, 2) do %>
              <li><%= link "LiveDashboard", to: Routes.live_dashboard_path(@conn, :home) %></li>
            <% end %>
          </ul>
        </nav>
        <a href="https://phoenixframework.org/" class="phx-logo">
          <img src={Routes.static_path(@conn, "/images/phoenix.png")} alt="Phoenix Framework Logo"/>
        </a>
      </section>
    </header>
    <%= @inner_content %>
  </body>
</html>

lib/sample_app_web/templates/page/index.html.heex
<section class="phx-hero">
  <h1><%= gettext "Welcome to %{name}!", name: "Phoenix" %></h1>
  <p>Peace of mind from prototype to production</p>
</section>

<section class="row">
  <article class="column">
    <h2>Resources</h2>
    <ul>
      <li>
        <a href="https://hexdocs.pm/phoenix/overview.html">Guides &amp; Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix/blob/v1.6/CHANGELOG.md">v1.6 Changelog</a>
      </li>
    </ul>
  </article>
  <article class="column">
    <h2>Help</h2>
    <ul>
      <li>
        <a href="https://elixirforum.com/c/phoenix-forum">Forum</a>
      </li>
      <li>
        <a href="https://web.libera.chat/#elixir">#elixir on Libera Chat (IRC)</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">Twitter @elixirphoenix</a>
      </li>
      <li>
        <a href="https://elixir-slackin.herokuapp.com/">Elixir on Slack</a>
      </li>
      <li>
        <a href="https://discord.gg/elixir">Elixir on Discord</a>
      </li>
    </ul>
  </article>
</section>

lib/sample_app_web/templates/static_page/about.html.heex
<h1>About</h1>
<p>
  The <a href="#"><em>Phoenix
  Tutorial</em></a> is a
  <a href="#">book</a>
  to teach web development with
  <a href="https://phoenixframework.org/">Phoenix</a>.
  This is the sample application for the tutorial.
</p>

lib/sample_app_web/templates/static_page/contact.html.heex
<h1>Contact</h1>
<p>
  Contact the Phoenix Tutorial about the sample app at the
  <a href="#">contact page</a>.
</p>

lib/sample_app_web/templates/static_page/help.html.heex
<h1>Help</h1>
<p>
  Get help on the Phoenix Tutorial at the
  <a href="#">Phoenix Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="#"><em>Phoenix Tutorial</em>
  book</a>.
</p>

lib/sample_app_web/templates/static_page/home.html.heex
<div class="hero-container container-fluid rounded p-5 mb-4">
  <div class="container text-center p-5">
    <h1>Welcome to the Sample App</h1>
    <h2>
      This is the home page for the
      <a href="#">Phoenix Tutorial</a>
      sample application.
    </h2>
    <%= link "Sign up now!", to: Routes.signup_path(@conn, :new),
    class: "btn btn-lg btn-primary" %>
  </div>
</div>
<%= link img_tag(Routes.static_path(@conn, "/images/phoenix.png"),
  alt: "Phoenix logo", width: 260, height: 40),
  to: "https://phoenixframework.org/" %>

lib/sample_app_web/templates/user/new.html.heex
<h1>Sign up</h1>
<p>This will be a signup page for new users.</p>